// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID       string `json:"id"`
	UserName string `json:"userName"`
}

type UserCreateInput struct {
	UserName string `json:"userName"`
}
